/* Generated By:JavaCC: Do not edit this line. nplpConstants.java */
// NPL parser

  package npl.parser;

public interface nplpConstants {

  int EOF = 0;
  int VAR = 7;
  int TK_NOT = 8;
  int TK_LABEL_AT = 9;
  int TK_INTDIV = 10;
  int TK_INTMOD = 11;
  int NUMBER = 12;
  int EXPONENT = 13;
  int STRING = 14;
  int NP = 15;
  int SCOPE = 16;
  int NORM = 17;
  int FAIL = 18;
  int OBLIGATION = 19;
  int ATOM = 20;
  int UNNAMEDVAR = 21;
  int CHAR = 22;
  int LETTER = 23;
  int LC_LETTER = 24;
  int UP_LETTER = 25;
  int DIGIT = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<VAR>",
    "\"not\"",
    "\"@\"",
    "\"div\"",
    "\"mod\"",
    "<NUMBER>",
    "<EXPONENT>",
    "<STRING>",
    "\"np\"",
    "\"scope\"",
    "\"norm\"",
    "\"fail\"",
    "\"obligation\"",
    "<ATOM>",
    "<UNNAMEDVAR>",
    "<CHAR>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\".\"",
    "\"}\"",
    "\":-\"",
    "\":\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\"&\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"\\\\==\"",
    "\"=\"",
    "\"=..\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"`\"",
  };

}
